name: Android CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Nuxt app
      run: npm run generate # Ensure the build command is correct

    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli

    - name: Check if Android platform exists
      id: check-android
      run: |
        if [ -d "./android" ]; then
          echo "exists=true" >> $GITHUB_ENV
        else
          echo "exists=false" >> $GITHUB_ENV
        fi

    - name: Add Android platform
      if: env.exists == 'false'
      run: npx cap add android

    - name: Sync Capacitor plugins
      run: npx cap sync

    - name: Copy web assets
      run: npx cap copy

    - name: Ensure cordova.variables.gradle exists
      run: |
        if [ ! -f "./android/capacitor-cordova-android-plugins/cordova.variables.gradle" ]; then
          mkdir -p ./android/capacitor-cordova-android-plugins
          echo "ext {" > ./android/capacitor-cordova-android-plugins/cordova.variables.gradle
          echo "    // Add any Cordova variables here" >> ./android/capacitor-cordova-android-plugins/cordova.variables.gradle
          echo "    // Example:" >> ./android/capacitor-cordova-android-plugins/cordova.variables.gradle
          echo "    // someVariableName = \"someValue\"" >> ./android/capacitor-cordova-android-plugins/cordova.variables.gradle
          echo "}" >> ./android/capacitor-cordova-android-plugins/cordova.variables.gradle
        fi

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Verify APK path and set environment variable
      id: verify-apk-path
      run: |
        if [ -f "android/app/build/outputs/apk/debug/app-debug.apk" ]; then
          echo "APK_PATH=android/app/build/outputs/apk/debug/app-debug.apk" >> $GITHUB_ENV
        elif [ -f "android/app/build/outputs/debug/app-debug.apk" ]; then
          echo "APK_PATH=android/app/build/outputs/debug/app-debug.apk" >> $GITHUB_ENV
        else
          echo "APK_PATH=not_found" >> $GITHUB_ENV
        fi

    - name: Fail if APK not found
      if: env.APK_PATH == 'not_found'
      run: exit 1

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: ${{ env.APK_PATH }}
